### ISSUE TITLE
npm-audit-ci-wrapper not working with npm CLI version 7

### ISSUE THREAD

**Issue by beornling** [InfoSec812/npm-audit-ci-wrapper#82]
Version 7 of the npm CLI changes the format of the audit JSON report, and this tool fails to parse the new format.

```
\node_modules\npm-audit-ci-wrapper\lib\parser.js:52
     const advisories = Object.entries(data.advisories);
                               ^
 TypeError: Cannot convert undefined or null to object
     at Function.entries (<anonymous>)
```

**Comment by InfoSec812** [comment]
I would love it if you could submit a pull-request. Otherwise, it may be a week or so before I can get around to updating. Also, I would suggest having a look at [AuditJS](https://www.npmjs.com/package/auditjs) from [Sonatype](https://github.com/sonatype-nexus-community). I have been using that more and more over the past few months.

**Comment by InfoSec812** [comment]
I highly recommend that you use Sonatype's auditjs as a replacement. I am just going to mark this project as deprecated.

**Comment by joebowbeer** [comment]
[npm-audit-resolver](https://github.com/naugtur/npm-audit-resolver) also has this issue but it is being addressed: https://github.com/naugtur/npm-audit-resolver/issues/34
